spring:
  application:
    name: F1 ELO System
  datasource:
    url: jdbc:postgresql://localhost:5432/f1_elo
    username: local
    password: local
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true

server:
  port: 8000
