spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/f1_elo
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jolpi-f1:
  base-url: https://api.jolpi.ca/ergast/f1

cron:
  job:
    enabled: true