spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    root: debug
    org.springframework.web: debug

jolpi-f1:
  base-url: https://api.jolpi.ca/ergast/f1

cron:
  job:
    enabled: true