spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jolpi-f1:
  base-url: https://api.jolpi.ca/ergast/f1

cron:
  job:
    enabled: true

auth:
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}
