version: '3.8'

services:
  prometheus:
    build:
      context: ./
      dockerfile: prometheus/Dockerfile
    container_name: prometheus
    restart: unless-stopped
    user: root
    ports:
      - "9090:9090"
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: f1_elo
    ports:
      - "5432:5432"