name: CD/CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Check 🔬
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Run gradle check
        run: ./gradlew check --stacktrace --no-configuration-cache

  security-scan:
    name: Security Scan 🔎
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Lava
        uses: adevinta/lava-action@v0

  typo-checker:
    name: Check typos in project 📚
    uses: crate-ci/typos@master