name: CD/CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

jobs:
  check:
    name: Check 🔬
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Run gradle check
        run: ./gradlew check --stacktrace --no-configuration-cache

  security-scan:
    name: Security Scan 🔎
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lava
        uses: adevinta/lava-action@v0

  typo-checker:
    name: Check typos in project 📚
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check typos
        uses: crate-ci/typos@master

  automerge:
    name: Auto-merge dependabot PRs
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    needs: [ check, security-scan ]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs:
      - check
      - typo-checker
      - security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy the application 🚀
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            git clone https://baaarbz:${{ secrets.GITHUB_TOKEN }}@github.com/Baaarbz/f1-elo.git
            sh f1-elo/deploy/deploy.sh
            rm -rf f1-elo